---
title: "Abiotic Factors (SST & PP) - Coral Group"
output: html_document
date: 6/3/20
by: M. Kawahara
---

```{r}
#Following code is from Bio-Oracle's website for integration with R
install.packages("sdmpredictors")
install.packages("leaflet")
install.packages("readr")

library(sdmpredictors)
library(leaflet)
list_datasets()
list_layers() #<-shows layer codes
layer_stats() #<-not sure what all the information is

```

**Sample code from website for maximum temperature at sea bottom**
```{r}
temp.max.bottom <- load_layers("BO2_tempmax_bdmax")
ne.atlantic.ext <- extent(-100, 45, 30.75, 72.5)
temp.max.bottom.crop <- crop(temp.max.bottom, ne.atlantic.ext)
my.colors = colorRampPalette(c("#5E85B8","#EDF0C0","#C13127"))
plot(temp.max.bottom.crop,col=my.colors(1000),axes=FALSE, box=FALSE)
title(cex.sub = 1.25, sub = "Maximum temperature at the sea bottom (ºC)")

```

**Mean Sea Surface Temperature**
```{r}
layers.bio2 <-list_layers( datasets="Bio-ORACLE" )

#Download environmental data layers (Sea surafce temperature and primary productivity at Sea Surface)
abiotic_factors<-load_layers(layercodes = c("BO2_tempmean_ss", "BO2_ppmean_ss"), equalarea=FALSE, rasterstack=TRUE)
#BO2_tempmean_ss = sea surface temperature mean - units in degrees celcius
#BO2_ppmean_bdmean = mean sea surface net primary productivity of carbon

#Upload unique lat;long list
latlongs<-read.csv("~/Desktop/2020_BayLab_Coral_Group/Acropora_UniqueLocations.csv")
lat<-latlongs$Latitude
long<-latlongs$Longitude

abiotic.sites<-data.frame(long, lat)
sst<-load_layers("BO2_tempmean_ss")
pp<-load_layers("BO2_ppmean_ss")

#Create dataset of values for SST and PP
abiotic.sites.environment<-data.frame(Name=abiotic.sites, depth=extract(sst,abiotic.sites[1:2]), extract(abiotic_factors, abiotic.sites[1:2]))
head.matrix(abiotic.sites.environment) #there is a column called "layer" but the values are the same as the ones in the SST so code in line 54 just pulls out the desired columns

names(abiotic_info)[names(abiotic_info)=="Name.long"] <-"Longitude"

abiotic_info<-abiotic.sites.environment[,c("Longitude","Latitude","BO2_tempmean_ss","BO2_ppmean_ss")]
View(abiotic_info)

#changed column names to merge with dataset that contains species name column
names(abiotic_info)[names(abiotic_info)=="Name.long"] <-"Longitude" 
names(abiotic_info)[names(abiotic_info)=="Name.lat"] <-"Latitude"


write.csv(abiotic_info, "Abiotic_Conditions_2.csv")
```


```{r}
#Visualize the sites on google maps
a<-leaflet()
a<-addTiles(a)
a<-addMarkers(a, lng=long,lat=lat, popup = abiotic.sites$Name)
a
```

**Mean Sea Surface Temp Graph for Hawaii**
```{r}
#Creating maps of the abiotic factors
HI<-extent(-162,-152,16,25) #"extent" is lat/long limits for the area
sst.HI.crop<-crop(sst,HI)

my.colors=colorRampPalette(c("#5E85B8","#EDF0C0","#C13127"))
plot(sst.HI.crop, col=my.colors(1000), axes=FALSE, box=FALSE) + title(cex.sub=1.25, sub="Mean Sea Surface Temperature")
```

**Mean Sea Surface Temp Graph for the Globe**
```{r}
world<-extent(-180,180,-50,50)
sst.globe<-crop(sst,world)

plot(sst.globe, col=my.colors(1000), axes=FALSE, box=FALSE) + title(cex.sub=1.25, sub="Mean Sea Surface Temperature")

```

**Merging Abiotic Factors with Genetic Data**
```{r}
#Didn't have a species column in abiotic_info so created one in order to merge it with the "gen" dataset
Species <-gen[,c("Longitude","Species")]
abiotic_merge<-merge(gen, abiotic, by.x=c("Latitude","Longitude","Species"), by.y=c("Latitude","Longitude","Species"))


imp.vars <- c("He.all","Species","Ocean",
              "Latitude","Longitude","Sample.year",
              "Number","Cross.species","Primer.note","BO2_tempmean_ss","BO2_ppmean_ss") #"He.all" is heterozygosity
sub <- abiotic_merge[,imp.vars]
nona <- na.omit(sub) # This framework doesn't handle missing data so the the more variables you include the more data you lose
dim(nona)
rf <- randomForest(He.all~.,data=nona)
rf # We can see % Variance explained here
varImpPlot(rf)



pairs(abiotic_merge[,c("Longitude","Latitude","BO2_tempmean_ss","BO2_ppmean_ss","Sample.year")]) 



```




